# theme: jekyll-theme-cayman
theme: minima
title: Paul Bares
subtitle: Home
description: 
domain: paulbares.me    
url: https://paulbares.me

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
