# theme: jekyll-theme-cayman
theme: minima
# title: Paul Bares
# subtitle: Home
description: Personal website
domain: paulbares.me    
url: https://paulbares.me

# social
linkedin_username: paulbares
github_username:  paulbares