# theme: jekyll-theme-cayman
theme: minima
title: Paul Bares
subtitle: Home
description: 
domain: paulbares.me    
url: https://paulbares.me


minima:
  social_links:
    twitter: jekyllrb
    github: jekyll
    stackoverflow: "11111"
    dribbble: jekyll
    facebook: jekyll
    flickr: jekyll
    instagram: jekyll
    linkedin: jekyll
    
social_links:
  twitter: jekyllrb
  github: jekyll
  stackoverflow: "11111"
  dribbble: jekyll
  facebook: jekyll
  flickr: jekyll
  instagram: jekyll
  linkedin: jekyll
